version: "3.3"

services:
  node:
    restart: unless-stopped
    container_name: ${PROJECT_NAME}
    ports:
      - ${PROJECT_PORTS}
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ${PROJECT_PATH}:/var/www
    command: sh -c "npm i && npx nodemon index.js"